apiVersion: apps/v1
kind: Deployment
metadata:
  name: podkiller-deployment
  labels:
    app: podkiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podkiller
  template:
    metadata:
      labels:
        app: podkiller
    spec:
      containers:
      - name: podkiller
        image: in-cluster:0.1.1